version: '3.4'

services:
  image1:
    build:
      context: image1/
      dockerfile: Dockerfile
    volumes:
      - "./image1:/root/server"
    tty: true
    stdin_open: true
  image2:
    build:
      context: image2/
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
  image3:
    build:
      context: image3/
      dockerfile: Dockerfile
    volumes:
      - "./image3:/root/server"
    tty: true
    stdin_open: true
  image4:
    build:
      context: image4/
      dockerfile: Dockerfile
    volumes:
      - "./image4:/root/server"
      - "image4-node_modules:/root/server/node_modules"
    tty: true
    stdin_open: true

volumes:
  image4-node_modules:
